name: Publish to OnePub

on:
  workflow_dispatch:
    inputs:
      increment:
        description: 'Which version segment to bump'
        required: true
        type: choice
        options:
          - minor
          - major

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Dart SDK
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Install OnePub CLI
        run: dart pub global activate onepub

      - name: Get dependencies
        run: dart pub get

      - name: Authenticate with OnePub
        run: onepub login --token ${{ secrets.ONEPUB_TOKEN }}

      - name: Bump version
        run: |
          if [ "${{ github.event.inputs.increment }}" = "major" ]; then
            dart pub global activate cider
            cider bump major
          elif [ "${{ github.event.inputs.increment }}" = "minor" ]; then
            dart pub global activate cider
            cider bump minor
          fi

      - name: Publish to OnePub
        run: onepub pub publish --force

      - name: Commit version bump
        run: |
          git config --local user.email "shashwat@circuskitchens.com"
          git config --local user.name "shashwatxx"
          git add .
          git commit -m "Bump version to $(dart pub deps --json | jq -r '.packages[] | select(.name == "hoverover") | .version')" || exit 0
          git push

