name: Publish to OnePub

on:
  workflow_dispatch:
    inputs:
      increment:
        description: 'Which version segment to bump'
        required: true
        type: choice
        options:
          - minor
          - major

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Dart SDK
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Install OnePub CLI
        run: dart pub global activate onepub

      - name: Authenticate to OnePub
        env:
          ONEPUB_TOKEN: ${{ secrets.ONEPUB_TOKEN }}
        run: |
          export PATH="$PATH:$HOME/.pub-cache/bin"
          onepub import

      - name: Bump version (${{ github.event.inputs.increment }})
        id: bump
        run: |
          dart pub bump ${{ github.event.inputs.increment }}
          echo "NEW_VERSION=$(dart pub version --machine | jq -r .version)" >> $GITHUB_OUTPUT

      - name: Publish to OnePub
        env:
          PUB_HOSTED_URL: https://onepub.dev
        run: dart pub publish --force

      - name: Tag and push release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "shashwatxx"
          git config user.email "shashwat@circuskitchens.com"
          git tag v${{ steps.bump.outputs.NEW_VERSION }}
          git push origin v${{ steps.bump.outputs.NEW_VERSION }}